// Mocks generated by Mockito 5.4.4 from annotations
// in flowery_rider/test/auth/data/data_source/logout_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flowery_rider/core/api/api_manager/api_manager.dart' as _i4;
import 'package:flowery_rider/features/auth/data/models/request/login_model_dto.dart'
    as _i6;
import 'package:flowery_rider/features/auth/data/models/response/login_response_dto.dart'
    as _i2;
import 'package:flowery_rider/features/auth/data/models/response/logout_response.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoginResponseDto_0 extends _i1.SmartFake
    implements _i2.LoginResponseDto {
  _FakeLoginResponseDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLogoutResponseDto_1 extends _i1.SmartFake
    implements _i3.LogoutResponseDto {
  _FakeLogoutResponseDto_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i4.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.LoginResponseDto> login(_i6.LoginModelDto? loginModelDto) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [loginModelDto],
        ),
        returnValue:
            _i5.Future<_i2.LoginResponseDto>.value(_FakeLoginResponseDto_0(
          this,
          Invocation.method(
            #login,
            [loginModelDto],
          ),
        )),
      ) as _i5.Future<_i2.LoginResponseDto>);

  @override
  _i5.Future<_i3.LogoutResponseDto> logout(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #logout,
          [token],
        ),
        returnValue:
            _i5.Future<_i3.LogoutResponseDto>.value(_FakeLogoutResponseDto_1(
          this,
          Invocation.method(
            #logout,
            [token],
          ),
        )),
      ) as _i5.Future<_i3.LogoutResponseDto>);
}
