// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXLs4WAH7YpGngBC-iOvqyY2kPeln8EXI',
    appId: '1:845994738611:web:0f96caee20a27664f541c6',
    messagingSenderId: '845994738611',
    projectId: 'flowery-ecommerce',
    authDomain: 'flowery-ecommerce.firebaseapp.com',
    storageBucket: 'flowery-ecommerce.firebasestorage.app',
    measurementId: 'G-C9GN1BXRRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgTY2g3HkaANARRP0cKxC9HcSCAbthMz8',
    appId: '1:845994738611:android:b31168573d3afe4bf541c6',
    messagingSenderId: '845994738611',
    projectId: 'flowery-ecommerce',
    storageBucket: 'flowery-ecommerce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEJO6ar2pNUQmx7caDMwhDd8AOGHby5pA',
    appId: '1:845994738611:ios:227144ee4e3b8080f541c6',
    messagingSenderId: '845994738611',
    projectId: 'flowery-ecommerce',
    storageBucket: 'flowery-ecommerce.firebasestorage.app',
    iosBundleId: 'com.example.floweryRider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEJO6ar2pNUQmx7caDMwhDd8AOGHby5pA',
    appId: '1:845994738611:ios:227144ee4e3b8080f541c6',
    messagingSenderId: '845994738611',
    projectId: 'flowery-ecommerce',
    storageBucket: 'flowery-ecommerce.firebasestorage.app',
    iosBundleId: 'com.example.floweryRider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLYutsTOQwFa-MhlnE28rGBtCi2LerPfw',
    appId: '1:845994738611:web:31c9eb8cb31e31e5f541c6',
    messagingSenderId: '845994738611',
    projectId: 'flowery-ecommerce',
    authDomain: 'flowery-ecommerce.firebaseapp.com',
    storageBucket: 'flowery-ecommerce.firebasestorage.app',
    measurementId: 'G-8D4GS8HZW0',
  );
}
